import esbuild from "esbuild";
import { execFileSync } from "child_process";
import { readFileSync } from "fs";
import { builtinModules } from "module";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const production = process.argv.includes("production");
const watch = process.argv.includes("watch");
const builtins = [
	...builtinModules,
	...builtinModules.map((name) => `node:${name}`),
];

function git(args) {
	try {
		return execFileSync("git", args, {
			encoding: "utf8",
			stdio: ["ignore", "pipe", "ignore"],
		}).trim();
	} catch {
		return "";
	}
}

function getBuildId() {
	const explicitBuildId = process.env.RELAY_COMMENTS_BUILD_ID?.trim();
	if (explicitBuildId) {
		return explicitBuildId;
	}

	const shortCommit = git(["rev-parse", "--short=7", "HEAD"]);
	if (!shortCommit) {
		return "dev";
	}

	const trackedChanges = git([
		"status",
		"--porcelain",
		"--untracked-files=no",
		"--",
		".",
		":(exclude)main.js",
	]);
	return trackedChanges ? `${shortCommit}-dirty` : shortCommit;
}

function getManifestVersion() {
	try {
		const manifest = JSON.parse(readFileSync("manifest.json", "utf8"));
		return typeof manifest.version === "string" && manifest.version.trim()
			? manifest.version.trim()
			: "0.0.0";
	} catch {
		return "0.0.0";
	}
}

const buildId = getBuildId();
const manifestVersion = getManifestVersion();

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/state",
		"@codemirror/view",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	minify: production,
	logLevel: "info",
	define: {
		__RELAY_COMMENTS_VERSION__: JSON.stringify(manifestVersion),
		__RELAY_COMMENTS_BUILD_ID__: JSON.stringify(buildId),
	},
	sourcemap: production ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (watch) {
	await context.watch();
	console.log("Watching Relay Comments plugin sources...");
} else {
	await context.rebuild();
	await context.dispose();
}
