import esbuild from "esbuild";
import builtins from "builtin-modules";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const production = process.argv.includes("production");
const watch = process.argv.includes("watch");

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/state",
		"@codemirror/view",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	minify: production,
	logLevel: "info",
	sourcemap: production ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (watch) {
	await context.watch();
	console.log("Watching Relay Comments plugin sources...");
} else {
	await context.rebuild();
	await context.dispose();
}
